// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolicitorFinder.Data;

#nullable disable

namespace SolicitorFinder.Data.Migrations
{
    [DbContext(typeof(SolicitorDbContext))]
    partial class SolicitorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolicitorFinder.Data.Models.AreaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SolicitorAreaExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Area_Name");

                    b.HasIndex("SolicitorAreaExternalId")
                        .HasDatabaseName("IX_Area_ExternalId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.ConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxResults")
                        .HasColumnType("int");

                    b.Property<int>("UpdateInterval")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConfigEntity");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfigEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigEntityId");

                    b.HasIndex("Title", "Text")
                        .HasDatabaseName("IX_Location_Title_Text");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.Solicitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("RatingStars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Solicitor_Name");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_Solicitor_Phone");

                    b.HasIndex("RatingStars", "ReviewCount")
                        .HasDatabaseName("IX_Solicitor_Rating_Reviews");

                    b.ToTable("Solicitors");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.SolicitorArea", b =>
                {
                    b.Property<int>("SolicitorId")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.HasKey("SolicitorId", "AreaId");

                    b.HasIndex("AreaId");

                    b.ToTable("SolicitorAreas");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.SolicitorLocation", b =>
                {
                    b.Property<int>("SolicitorId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("SolicitorId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("SolicitorLocations");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.Location", b =>
                {
                    b.HasOne("SolicitorFinder.Data.Models.ConfigEntity", "Config")
                        .WithMany("Locations")
                        .HasForeignKey("ConfigEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Config");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.SolicitorArea", b =>
                {
                    b.HasOne("SolicitorFinder.Data.Models.AreaEntity", "Area")
                        .WithMany("SolicitorArea")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolicitorFinder.Data.Models.Solicitor", "Solicitor")
                        .WithMany("SolicitorAreas")
                        .HasForeignKey("SolicitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Solicitor");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.SolicitorLocation", b =>
                {
                    b.HasOne("SolicitorFinder.Data.Models.Location", "Location")
                        .WithMany("SolicitorsLocation")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolicitorFinder.Data.Models.Solicitor", "Solicitor")
                        .WithMany("SolicitorLocations")
                        .HasForeignKey("SolicitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Solicitor");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.AreaEntity", b =>
                {
                    b.Navigation("SolicitorArea");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.ConfigEntity", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.Location", b =>
                {
                    b.Navigation("SolicitorsLocation");
                });

            modelBuilder.Entity("SolicitorFinder.Data.Models.Solicitor", b =>
                {
                    b.Navigation("SolicitorAreas");

                    b.Navigation("SolicitorLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
